// <auto-generated />
namespace CDLRouteHelper.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class removeAddress2fromBridge : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removeAddress2fromBridge));
        
        string IMigrationMetadata.Id
        {
            get { return "201310061924197_removeAddress2fromBridge"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
