// <auto-generated />
namespace CDLRouteHelper.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class moveWeightFieldFromBridgetoWeight : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(moveWeightFieldFromBridgetoWeight));
        
        string IMigrationMetadata.Id
        {
            get { return "201309231826125_moveWeightFieldFromBridgetoWeight"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
