// <auto-generated />
namespace CDLRouteHelper.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class User_toUserAddressLookup : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(User_toUserAddressLookup));
        
        string IMigrationMetadata.Id
        {
            get { return "201309241922546_User_toUserAddressLookup"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
